/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelado.Usuario;
import java.util.ArrayList;

/**
 *
 * @author bryan
 */
public class pantallaDenuncias extends javax.swing.JFrame {

    Usuario usuario;
    Integer desicion;
    public pantallaDenuncias(Usuario usuarioNecesario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario=usuarioNecesario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearDenunciaBttt = new javax.swing.JButton();
        denunciasBtt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearDenunciaBttt.setText("HACER DENUNCIA");
        crearDenunciaBttt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearDenunciaBtttActionPerformed(evt);
            }
        });
        getContentPane().add(crearDenunciaBttt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, -1));

        denunciasBtt.setText("VER DENUNCIAS");
        denunciasBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denunciasBttActionPerformed(evt);
            }
        });
        getContentPane().add(denunciasBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/pantallasPequeñas.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 240, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void denunciasBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denunciasBttActionPerformed
        // TODO add your handling code here:
        pantallaImprimirDenuncias imprimirDenuncias= new pantallaImprimirDenuncias(this.usuario);
        imprimirDenuncias.setVisible(true);
        imprimirDenuncias.imprimirDenuncias();
        this.setVisible(false);
    }//GEN-LAST:event_denunciasBttActionPerformed

    private void crearDenunciaBtttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearDenunciaBtttActionPerformed
        // TODO add your handling code here:
        pantallaCrearDenuncias crearDenuncia= new pantallaCrearDenuncias(this.usuario);
        crearDenuncia.setVisible(true);
        this.setVisible(false);
       
        
    }//GEN-LAST:event_crearDenunciaBtttActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:+
   
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearDenunciaBttt;
    private javax.swing.JButton denunciasBtt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
