/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelado.Usuario;
import java.util.ArrayList;

/**
 *
 * @author bryan
 */
public class pantallaLogear extends javax.swing.JFrame {

    ArrayList<Usuario> usuarios;
    Integer desicion;
    public pantallaLogear(ArrayList<Usuario> usuarioNecesarios, Integer desicion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarios=usuarioNecesarios;
        this.desicion= desicion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginButton = new javax.swing.JButton();
        txtContraseña = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, -1));

        jLabel1.setText("CONTRASEÑA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        getContentPane().add(txtError, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, -1));

        backbutton.setText("VOLVER");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/pantallasPequeñas.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 260, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        int idIngresado = Integer.parseInt(this.txtID.getText());
        String contraseñaIngresada= this.txtContraseña.getText();
        int c=0;
        
        while(c!= this.usuarios.size()){
            int idComparar= this.usuarios.get(c).getId();
            String contraseñaComparar= this.usuarios.get(c).getPassword();
            if(idComparar==idIngresado){
                if(contraseñaIngresada.equals(contraseñaComparar)){
                    
                    pantallaDenuncias pantallaDenuncia= new  pantallaDenuncias(this.usuarios.get(c));
                    pantallaDenuncia.setVisible(true);
                    this.txtError.setText("EXITO");
                    this.setVisible(false);
                    break;
                    
                }else{
                    this.txtError.setText("CONTRASEÑA INCORRECTA");
                    break;
                }
            }else{
                c++;
            }
            this.txtError.setText("CUENTA NO ENCONTRADA");
        }
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
