/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelado.Cuenta;

/**
 *
 * @author bryan
 */
public class selectProcessView extends javax.swing.JFrame {
    Cuenta cuenta;
    /**
     * Creates new form selectProcessView
     */
    public selectProcessView(Cuenta cuenta) {
        initComponents();
        this.cuenta=cuenta;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        depositMoneyButton = new javax.swing.JButton();
        withdrawalsButton = new javax.swing.JButton();
        balanceButton = new javax.swing.JButton();
        balanceButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        depositMoneyButton.setText("DEPOSIT MONEY");
        depositMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositMoneyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(depositMoneyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 189, -1));

        withdrawalsButton.setText("WITHDRAWALS");
        withdrawalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawalsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, 189, -1));

        balanceButton.setText("SEE BALANCE");
        balanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(balanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 78, 189, -1));

        balanceButton1.setText("EXIT ACOUNT");
        balanceButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(balanceButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 177, 189, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/bryan/NetBeansProjects/B-ATM/IMAGENES/instrucciones.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -1, 510, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void depositMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositMoneyButtonActionPerformed
        // TODO add your handling code here:
        moneyInteractionsView event= new moneyInteractionsView(cuenta);
        event.setVisible(true);
    }//GEN-LAST:event_depositMoneyButtonActionPerformed

    private void withdrawalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalsButtonActionPerformed
        // TODO add your handling code here:
        moneyInteractionsViewLess event= new moneyInteractionsViewLess(cuenta);
        event.setVisible(true);
    }//GEN-LAST:event_withdrawalsButtonActionPerformed

    private void balanceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_balanceButton1ActionPerformed

    private void balanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceButtonActionPerformed
        // TODO add your handling code here:
        clientInformation printBalance= new clientInformation(cuenta);
        printBalance.getTextArea().setText(cuenta.toString());
        printBalance.setVisible(true);
        
    }//GEN-LAST:event_balanceButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceButton;
    private javax.swing.JButton balanceButton1;
    private javax.swing.JButton depositMoneyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton withdrawalsButton;
    // End of variables declaration//GEN-END:variables
}
