/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelado.Usuario;
import java.util.ArrayList;

/**
 *
 * @author bryan
 */
public class pantallaLoginRegistro extends javax.swing.JFrame {

    ArrayList<Usuario> usuarios;
    Integer desicion;
    public pantallaLoginRegistro(ArrayList<Usuario> usuarioNecesarios, Integer desicion) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarios=usuarioNecesarios;
        this.desicion= desicion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarButton = new javax.swing.JButton();
        loginButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarButton.setText("REGISTRARSE");
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        loginButton1.setText("LOGIN");
        loginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jButton1.setText("VOLVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/pantallasPequeñas.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 270, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(this.desicion==1){
            pantallaLogear logAgente= new pantallaLogear(this.usuarios, this.desicion);
            logAgente.setVisible(true);
            this.setVisible(false);
        }else{
            pantallaLogear logUsuario= new pantallaLogear(this.usuarios, this.desicion);
            logUsuario.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_loginButton1ActionPerformed

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        if(this.desicion==1){
            pantallaRegistrarOIJ pantallaOij= new pantallaRegistrarOIJ(this.usuarios);
            pantallaOij.setVisible(true);
        }else{
            pantallaRegistrarUsuario pantallaUs= new pantallaRegistrarUsuario(this.usuarios);
            pantallaUs.setVisible(true);
            
        }
        
    }//GEN-LAST:event_registrarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton1;
    private javax.swing.JButton registrarButton;
    // End of variables declaration//GEN-END:variables
}
