/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelado.Denuncia;
import Modelado.DenunciaGeografica;
import Modelado.Usuario;
import static java.lang.Thread.sleep;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bryan
 */
public class pantallaCrearDenuncias extends javax.swing.JFrame {

    Usuario usuarioAImprimir;
    public pantallaCrearDenuncias(Usuario usuarioAImprimir) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarioAImprimir=usuarioAImprimir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        generarDenunciaNorma = new javax.swing.JButton();
        txtMont = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtY = new javax.swing.JTextField();
        generarDenunciaGeograficA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCausa = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("/");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 10, -1));

        generarDenunciaNorma.setText("GENERAR DENUNCIA");
        generarDenunciaNorma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarDenunciaNormaActionPerformed(evt);
            }
        });
        getContentPane().add(generarDenunciaNorma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        txtMont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontActionPerformed(evt);
            }
        });
        getContentPane().add(txtMont, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 50, -1));

        txtDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayActionPerformed(evt);
            }
        });
        getContentPane().add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, -1));

        jLabel2.setText("/");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 20, 20));

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        getContentPane().add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, -1));

        jLabel3.setText("d");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 20, -1));

        jLabel4.setText("y");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 20, -1));

        jLabel5.setText("m");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 20, -1));

        jLabel6.setText("Hora de los sucesos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, -1));

        jLabel7.setText("Causa:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel8.setText("OPCIONAL*:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel9.setText("x:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));
        getContentPane().add(txtX, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 120, 100, -1));

        jLabel10.setText("y:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));
        getContentPane().add(txtY, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 120, 100, -1));

        generarDenunciaGeograficA.setText("GENERAR DENUNCIA GEOGRAFICA");
        generarDenunciaGeograficA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarDenunciaGeograficAActionPerformed(evt);
            }
        });
        getContentPane().add(generarDenunciaGeograficA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        txtCausa.setColumns(20);
        txtCausa.setRows(5);
        jScrollPane1.setViewportView(txtCausa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 450, 110));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/pantallaDenuncias.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -80, 600, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarDenunciaNormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarDenunciaNormaActionPerformed
        // TODO add your handling code here:
        int year= Integer.parseInt(this.txtYear.getText());
        int day= Integer.parseInt(this.txtDay.getText());
        int mounth= Integer.parseInt(this.txtMont.getText());       
        Date fecha = new Date(year, mounth, day);
        Denuncia denunciaFormal= new Denuncia(this.usuarioAImprimir, this.txtCausa.getText(), fecha, this.txtHora.getText());
        this.usuarioAImprimir.getDenunciasHechas().add(denunciaFormal);
        System.out.println("Denuncia Tramitada");
        this.setVisible(false);
    }//GEN-LAST:event_generarDenunciaNormaActionPerformed

    private void txtMontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontActionPerformed

    private void txtDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void generarDenunciaGeograficAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarDenunciaGeograficAActionPerformed
        // TODO add your handling code here:
        int year= Integer.parseInt(this.txtYear.getText());
        int day= Integer.parseInt(this.txtDay.getText());
        int mounth= Integer.parseInt(this.txtMont.getText());       
        Date fecha = new Date(year, mounth, day);

        DenunciaGeografica denunciaFormal= new DenunciaGeografica(Double.parseDouble(this.txtX.getText()),Double.parseDouble(this.txtY.getText()),this.usuarioAImprimir, this.txtCausa.getText(), fecha, this.txtHora.getText());
        this.usuarioAImprimir.getDenunciasHechas().add(denunciaFormal);
        this.setVisible(false);
                                 
    }//GEN-LAST:event_generarDenunciaGeograficAActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generarDenunciaGeograficA;
    private javax.swing.JButton generarDenunciaNorma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtCausa;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMont;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
