/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelado.Cuenta;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author bryan
 */
public class CreateAccountView extends javax.swing.JFrame {
    
    MainView principal;
     ArrayList<Cuenta> Cuenta;
    /**
     * Creates new form CreateAccountView
     */
    public CreateAccountView(MainView principal, ArrayList<Cuenta> Cuenta) {
        initComponents();
        this.Cuenta=Cuenta;
        this.principal=principal;
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        monthTextFild = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yearTextFild = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nameTxFiild = new javax.swing.JTextField();
        idTxFiild1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        intAnuTxtFild = new javax.swing.JTextField();
        backButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        balanceText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idLabel.setText("ID:");
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 65, -1, -1));

        nombreLabel.setText("NOMBRE ASOCIADO:");
        getContentPane().add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel1.setText("FECHA DE CREACION:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        getContentPane().add(monthTextFild, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 34, -1));

        jLabel2.setText("/");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));
        getContentPane().add(dayTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 34, -1));

        jLabel3.setText("/");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));
        getContentPane().add(yearTextFild, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 34, -1));

        jButton1.setText("CREAR CUENTAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        nameTxFiild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxFiildActionPerformed(evt);
            }
        });
        getContentPane().add(nameTxFiild, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 130, -1));

        idTxFiild1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxFiild1ActionPerformed(evt);
            }
        });
        getContentPane().add(idTxFiild1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, -1));

        jLabel4.setText("INTERES ANUAL:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        intAnuTxtFild.setText("0.45");
        intAnuTxtFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intAnuTxtFildActionPerformed(evt);
            }
        });
        getContentPane().add(intAnuTxtFild, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 100, -1));

        backButton2.setText("BACK");
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(backButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        jLabel5.setText("d");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 30, -1));

        jLabel6.setText("y");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 30, -1));

        jLabel7.setText("m");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 30, -1));

        jLabel8.setText("BALANCE:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        balanceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceTextActionPerformed(evt);
            }
        });
        getContentPane().add(balanceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 120, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("/home/bryan/NetBeansProjects/B-ATM/IMAGENES/createAcount.jpg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intAnuTxtFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intAnuTxtFildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intAnuTxtFildActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backButton2ActionPerformed

    private void idTxFiild1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxFiild1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxFiild1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name= this.nameTxFiild.getText();
        int id= Integer.parseInt(this.idTxFiild1.getText());
        int day= Integer.parseInt(this.dayTextField.getText());
        int mount= Integer.parseInt(this.monthTextFild.getText());
        int year= Integer.parseInt(this.yearTextFild.getText());
        Double balance= Double.parseDouble(this.balanceText.getText());
        Date fecha= new Date(year, mount, day);
        Cuenta nueva= new Cuenta(name, id, balance, balance, fecha);
        this.Cuenta.add(nueva);
        System.out.println("Cuenta Añadida");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nameTxFiildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxFiildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxFiildActionPerformed

    private void balanceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton2;
    private javax.swing.JTextField balanceText;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTxFiild1;
    private javax.swing.JTextField intAnuTxtFild;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField monthTextFild;
    private javax.swing.JTextField nameTxFiild;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField yearTextFild;
    // End of variables declaration//GEN-END:variables
}
