/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelado.Cuenta;
import java.util.ArrayList;

/**
 *
 * @author bryan
 */
public class loginView extends javax.swing.JFrame {
    
    ArrayList<Cuenta> cuenta;
    /**
     * Creates new form loginView
     */
    public loginView(ArrayList<Cuenta> cuentas) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cuenta=cuentas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameVerificationtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        idVerificationtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tryTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 26, -1, -1));
        getContentPane().add(nameVerificationtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 63, 134, -1));

        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 100, 39, -1));
        getContentPane().add(idVerificationtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 131, 134, -1));

        jButton1.setText("TRY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 168, -1, -1));
        getContentPane().add(tryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 211, 97, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/bryan/NetBeansProjects/B-ATM/IMAGENES/login.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 360, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombreABuscar= this.nameVerificationtxt.getText();
        int idABuscar= Integer.parseInt(this.idVerificationtxt.getText());
        int i=0;
        while(i!= cuenta.size()){
            System.out.println(cuenta.size());
            if(cuenta.get(i).getNombre().equals(nombreABuscar)){
                if(cuenta.get(i).getId().equals(idABuscar)){
                    selectProcessView next= new selectProcessView(cuenta.get(i));
                    this.setVisible(false);
                    next.setVisible(true);
                    System.out.println("EXITO");
                }
            }
            i++;
        }
        
        this.tryTxt.setText("ERROR");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idVerificationtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameVerificationtxt;
    private javax.swing.JTextField tryTxt;
    // End of variables declaration//GEN-END:variables
}
