/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import modelado.ClaseApoyo;
import modelado.Ingrediente;
import modelado.Platillo;
import modelado.Usuario;

/**
 *
 * @author bryan
 */
public class pantallaMenu extends javax.swing.JFrame {
    
    ArrayList<Usuario> clientes;
    ArrayList<Usuario> cocineros;
    ArrayList<Usuario> administradores;
    ArrayList<Ingrediente> almacen;
    ArrayList<Platillo> oferta;

    /**
     * Creates new form 
     */
    public pantallaMenu(ArrayList<Usuario> clientes, ArrayList<Usuario> cocineros, ArrayList<Usuario> administradores, ArrayList<Ingrediente> almacen, ArrayList<Platillo> oferta) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.clientes= clientes;
        this.cocineros= cocineros;
        this.administradores= administradores;
        this.almacen=almacen;
        this.oferta=oferta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jButton1.setText("Perspectiva Administrador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 320, 190, 25);

        jButton2.setText("Perspectiva Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 220, 190, 25);

        jButton3.setText("Perspectiva Cocinero");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 270, 190, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Recursos Graficos/PantallaMenu.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 500, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       pantallaSeleccion seleccion= new pantallaSeleccion(clientes, 1, almacen, oferta);
       seleccion.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       pantallaSeleccion seleccion= new pantallaSeleccion(cocineros, 2, almacen, oferta);
       seleccion.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       pantallaSeleccion seleccion= new pantallaSeleccion(administradores, 3, almacen, oferta);
       seleccion.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
