/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import modelado.ClaseApoyo;
import modelado.Usuario;

/**
 *
 * @author bryan
 */
public class pantallaCreadoraDePerfilAlimenticio extends javax.swing.JFrame {

    ArrayList<String> gustos;
    ArrayList<String> alergias;
    public pantallaCreadoraDePerfilAlimenticio(ArrayList<String> gustos,ArrayList<String> alergias) {
       initComponents();
       this.setLocationRelativeTo(null);
       this.gustos=gustos;
       this.alergias=alergias;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbutton = new javax.swing.JButton();
        bttAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAlergia = new javax.swing.JTextField();
        labelConfirmar = new javax.swing.JLabel();
        txtEtiqueta1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bttAdd2 = new javax.swing.JButton();
        labelConfirmar2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(382, 356));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbutton.setText("Volver");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        bttAdd.setText("Añadir");
        bttAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddActionPerformed(evt);
            }
        });
        getContentPane().add(bttAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, 20));

        jLabel2.setText("Puedes añadir tus alergias, solo una palabra a la vez");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        getContentPane().add(txtAlergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 330, -1));
        getContentPane().add(labelConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 100, 30));
        getContentPane().add(txtEtiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 330, -1));

        jLabel3.setText("Puedes añadir tus gustos, solo una palabra a la vez");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        bttAdd2.setText("Añadir");
        bttAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAdd2ActionPerformed(evt);
            }
        });
        getContentPane().add(bttAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 20));
        getContentPane().add(labelConfirmar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 110, 30));

        jLabel1.setText("Por el momento solo ofrecemos, estas categorias:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setText("Vegetarian@, Vegan@, Libre de Gluten, Kosher, Halal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Recursos Graficos/LogoHoyComo.png"))); // NOI18N
        jLabel5.setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 490, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void bttAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddActionPerformed
        // TODO add your handling code here:
        String texto= this.txtEtiqueta1.getText();
        this.gustos.add(texto);
        this.labelConfirmar.setText("Añadido");
        this.txtEtiqueta1.setText("");
        
        
    }//GEN-LAST:event_bttAddActionPerformed

    private void bttAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAdd2ActionPerformed
        // TODO add your handling code here:
        String texto= this.txtAlergia.getText();
        this.alergias.add(texto);
        this.labelConfirmar2.setText("Añadido");
        this.txtEtiqueta1.setText("");
    }//GEN-LAST:event_bttAdd2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton bttAdd;
    private javax.swing.JButton bttAdd2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelConfirmar;
    private javax.swing.JLabel labelConfirmar2;
    private javax.swing.JTextField txtAlergia;
    private javax.swing.JTextField txtEtiqueta1;
    // End of variables declaration//GEN-END:variables
}
