/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.Base64;
import modelado.Administrador;
import modelado.Cocinero;
import modelado.Usuario;

/**
 *
 * @author bryan
 */
public class pantallaCrearGeneral extends javax.swing.JFrame {

    /**
     * Creates new form prototipo
     */
    ArrayList<Usuario> usuarios;
    int tipo=0;
    public pantallaCrearGeneral(ArrayList<Usuario> usuarios, int tipo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarios=usuarios;
        this.tipo=tipo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre De Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 110, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, -1));

        jLabel3.setText("Nombre: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 110, -1));

        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        jButton1.setText("!Todo listo!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Recursos Graficos/PantallaAddSistema.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre= this.txtNombre.getText();
        String usuarioID= this.txtUsuario.getText();
        String password= this.txtPassword.getText();
        String passwordCodificada = Base64.getEncoder().encodeToString(password.getBytes());
        
        if(tipo==2){
           Cocinero nuevoCocinero =new Cocinero(usuarioID, passwordCodificada, nombre);
            this.usuarios.add(nuevoCocinero);
            System.out.println("############COCINERO#################");
            System.out.println(nuevoCocinero.toString());
            System.out.println("############COCINERO#################");
            System.out.println("\n");
            System.out.println("############TODOS LOS COCINEROS#################");
            System.out.println(this.usuarios.toString());
            System.out.println("############TODOS LOS COCINEROS#################");
            this.setVisible(false);
        }else if(tipo==3){
            Administrador nuevoAdmi= new Administrador(usuarioID, passwordCodificada, nombre);
            this.usuarios.add(nuevoAdmi);
            System.out.println("############ADMI#################");
            System.out.println(nuevoAdmi.toString());
            System.out.println("############ADMI#################");
            System.out.println("\n");
            System.out.println("############TODOS LOS ADMI#################");
            System.out.println(this.usuarios.toString());
            System.out.println("############TODOS LOS ADMI#################");
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
