/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import modelado.ClaseApoyo;
import modelado.Cliente;
import modelado.Ingrediente;
import modelado.Platillo;
import modelado.Usuario;

/**
 *
 * @author bryan
 */
public class pantallaLogear extends javax.swing.JFrame {

    ArrayList<Usuario> usuarios;
    ClaseApoyo apoyo;
    ArrayList<Ingrediente> almacen;
    ArrayList<Platillo> oferta;
    int tipo=0;
    public pantallaLogear(ArrayList<Usuario> usuarios, ClaseApoyo apoyo, int tipo, ArrayList<Ingrediente> almacen,ArrayList<Platillo> oferta) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarios=usuarios;
        this.apoyo=apoyo;
        this.tipo=tipo;
        this.almacen=almacen;
        this.oferta=oferta;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginButton = new javax.swing.JButton();
        txtContraseña = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, -1));

        jLabel1.setText("Contraseña:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
        getContentPane().add(txtError, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, -1));

        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, -1));

        backbutton.setText("Volver");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Recursos Graficos/PantallaSeleccionPequeñas.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 250, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        int validacion=apoyo.login(usuarios, this.txtID.getText(), this.txtContraseña.getText());
       if(validacion==1){
           if(this.tipo==1){
               Cliente clienteLogueado= (Cliente) apoyo.getCuentaUsuario();
               pantallaCliente opcionesCliente= new pantallaCliente(clienteLogueado, oferta);
               opcionesCliente.setVisible(true);
               this.setVisible(false);
           }else if(this.tipo==2){
               pantallaCocinero opcionesCocinero= new pantallaCocinero(this.almacen, this.oferta);
               opcionesCocinero.setVisible(true);
               this.setVisible(false);
           }else if(this.tipo==3){
               pantallaAdministrador opcionesAdministrador= new pantallaAdministrador(this.almacen);
               opcionesAdministrador.setVisible(true);
               this.setVisible(false);
           }
           System.out.println("HIT");
           
       }else if(validacion==2){
           System.out.println("Contraseña incorrecta");
       }else{
           System.out.println("Cuenta no encontrada");
       }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
