/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import modelado.Ingrediente;

/**
 *
 * @author bryan
 */
public class pantallaCrearIngredientes extends javax.swing.JFrame {

    /**
     * Creates new form prototipo
     */
    ArrayList<String> personasQueLoPuedenComer;
    ArrayList<Ingrediente> almacen;
    boolean pezuña;
    boolean gluten;
    public pantallaCrearIngredientes(ArrayList<Ingrediente> almacen) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.personasQueLoPuedenComer= new ArrayList();
        this.almacen=almacen;
        this.pezuña=true;
        this.gluten=false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCosto = new javax.swing.JTextField();
        txtEtiqueta3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtUnidad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bttSíGlutten = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        bttSí1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);
        getContentPane().add(txtCosto);
        txtCosto.setBounds(30, 270, 110, 25);
        getContentPane().add(txtEtiqueta3);
        txtEtiqueta3.setBounds(30, 210, 110, 25);

        jLabel10.setText("Costo:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 250, 38, 19);

        jLabel1.setText("Unidad:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 120, 47, 19);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 20, 53, 19);

        jLabel3.setText("Cantidad:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 70, 57, 19);
        getContentPane().add(txtCantidad);
        txtCantidad.setBounds(100, 70, 110, 25);
        getContentPane().add(txtUnidad);
        txtUnidad.setBounds(100, 120, 110, 25);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(100, 20, 110, 25);

        jLabel4.setText("partida por favor presiona sí");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 40, 168, 19);

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 210, 72, 25);

        jButton2.setText("Añadir Ingrediente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 310, 142, 25);

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 330, 72, 25);

        jLabel5.setText("Tipo de alimento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 160, 105, 19);

        jLabel6.setText("Si procede de origen animal con pezuña");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 20, 237, 19);

        bttSíGlutten.setText("Sí");
        bttSíGlutten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSíGluttenActionPerformed(evt);
            }
        });
        getContentPane().add(bttSíGlutten);
        bttSíGlutten.setBounds(340, 130, 60, 25);

        jLabel8.setText("(Si es Carne de cerdo, especificar)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 180, 209, 19);

        bttSí1.setText("Sí");
        bttSí1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSí1ActionPerformed(evt);
            }
        });
        getContentPane().add(bttSí1);
        bttSí1.setBounds(340, 70, 60, 25);

        jLabel9.setText("Si contiene gluten por favor presion sí");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 100, 226, 19);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Recursos Graficos/PantallaIngredientes.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Ingrediente nuevoIngrediente= new Ingrediente(this.txtNombre.getText(), Integer.parseInt(this.txtCantidad.getText()), this.txtUnidad.getText(), this.personasQueLoPuedenComer, this.pezuña, this.gluten,Integer.parseInt(this.txtCosto.getText()));
        almacen.add(nuevoIngrediente);
        this.setVisible(false);
        System.out.println("############INGREDIENTE#################");
        System.out.println(nuevoIngrediente.toString());
        System.out.println("############INGREDIENTE#################");
        System.out.println("\n");
        System.out.println("############TODOS LOS INGREDIENTE#################");
        System.out.println(this.almacen.toString());
        System.out.println("############TODOS LOS INGREDIENTE#################");



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:47
        this.personasQueLoPuedenComer.add(this.txtEtiqueta3.getText());
        this.txtEtiqueta3.setText("");
        System.out.println("Añadido!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bttSíGluttenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSíGluttenActionPerformed
        // TODO add your handling code here:
        this.gluten= true;
    }//GEN-LAST:event_bttSíGluttenActionPerformed

    private void bttSí1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSí1ActionPerformed
        // TODO add your handling code here:
        this.pezuña=false;
    }//GEN-LAST:event_bttSí1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttSí1;
    private javax.swing.JButton bttSíGlutten;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtEtiqueta3;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
