/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import modelado.Ingrediente;
import modelado.Platillo;

/**
 *
 * @author bryan
 */
public class pantallaCrearPlatillo extends javax.swing.JFrame {

    /**
     * Creates new form prototipo
     */
    ArrayList<Ingrediente> almacen;
    ArrayList<Platillo> oferta;
    Ingrediente nuevoIngrediente;
    ArrayList<Ingrediente> ingredientesDePlatillos;
    int t=0;
    int k=0;
    
    public pantallaCrearPlatillo(ArrayList<Ingrediente> almacen,ArrayList<Platillo> oferta) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.almacen= almacen;
        this.oferta=oferta;
        this.ingredientesDePlatillos= new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        bttVerif1 = new javax.swing.JButton();
        hitFailNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        bttVef2 = new javax.swing.JButton();
        hitFailCantidad = new javax.swing.JTextField();
        addIngrediente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceta = new javax.swing.JTextArea();
        bttPlatillo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombrePlatillo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Para crear platillos introduce el nombre del ingrediente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, -1));

        bttVerif1.setText("Verificar");
        bttVerif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVerif1ActionPerformed(evt);
            }
        });
        getContentPane().add(bttVerif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        hitFailNombre.setEditable(false);
        getContentPane().add(hitFailNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        jLabel2.setText("Lo siguiente es considerar si hay lo suficiente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, -1));

        bttVef2.setText("Verificar");
        bttVef2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVef2ActionPerformed(evt);
            }
        });
        getContentPane().add(bttVef2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        hitFailCantidad.setEditable(false);
        getContentPane().add(hitFailCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, -1));

        addIngrediente.setText("Añadir Ingrediente");
        addIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngredienteActionPerformed(evt);
            }
        });
        getContentPane().add(addIngrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel3.setText("Lo ultimo es indicar la receta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtReceta.setColumns(20);
        txtReceta.setRows(5);
        jScrollPane1.setViewportView(txtReceta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 270, -1));

        bttPlatillo.setText("Crear Platillo");
        bttPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPlatilloActionPerformed(evt);
            }
        });
        getContentPane().add(bttPlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jLabel4.setText("Nombre del platillo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));
        getContentPane().add(txtNombrePlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 140, -1));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        jLabel5.setText("Entrada, Postre, Fuerte, Bebida?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));
        getContentPane().add(txtEte, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 140, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Recursos Graficos/PantallaRegistro.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttVerif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVerif1ActionPerformed
        // TODO add your handling code here:
        
        String nombre= this.txtNombre.getText();
        int c=0;
        int h=0;
        while(c!=this.almacen.size()){
            
            if(nombre.equals(this.almacen.get(c).getNombre())){
                this.nuevoIngrediente= this.almacen.get(c);
                h=c;
                k=c;
                t=this.almacen.get(c).getCantidad();
                this.hitFailNombre.setText("Sí hay!");
            }
            c++;
        }
        
        if(nombre.equals(this.almacen.get(h).getNombre())){
            this.hitFailNombre.setText("Sí hay!");
        }else{
            this.hitFailNombre.setText("No hay!");
            this.nuevoIngrediente= null;
        }
    
    }//GEN-LAST:event_bttVerif1ActionPerformed

    private void bttVef2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVef2ActionPerformed
        // TODO add your handling code here:
        if(this.nuevoIngrediente.getCantidad()>=Integer.parseInt(this.txtCantidad.getText())){
            this.hitFailCantidad.setText("Hay suficiente!");
            this.nuevoIngrediente.setCantidad(Integer.parseInt(this.txtCantidad.getText()));
        }else{
            this.hitFailCantidad.setText("No hay suficiente!");
        }
    }//GEN-LAST:event_bttVef2ActionPerformed

    private void addIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngredienteActionPerformed
        // TODO add your handling code here:
        if(this.nuevoIngrediente==null){
            System.out.println("No hay ese ingrediente en el almacen");
        }else{
            this.ingredientesDePlatillos.add(this.nuevoIngrediente);
            System.out.println("Ingrediente Añadido");
            this.txtNombre.setText("");
            this.txtCantidad.setText("");
            this.nuevoIngrediente=null;
        }
    }//GEN-LAST:event_addIngredienteActionPerformed

    private void bttPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPlatilloActionPerformed
        // TODO add your handling code here:
        Platillo nuevoPlatillo= new Platillo(ingredientesDePlatillos, this.txtNombrePlatillo.getText(), this.txtReceta.getText(), this.txtEte.getText());
        this.oferta.add(nuevoPlatillo);
        this.setVisible(false);

        System.out.println("############PLATILLO#################");
        System.out.println(nuevoPlatillo.toString());
        System.out.println("############PLATILLO#################");
        System.out.println("\n");
        System.out.println("############TODOS LOS PLATILLOS#################");
        System.out.println(this.oferta.toString());
        System.out.println("############TODOS LOS PLATILLOS#################");
    }//GEN-LAST:event_bttPlatilloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIngrediente;
    private javax.swing.JButton bttPlatillo;
    private javax.swing.JButton bttVef2;
    private javax.swing.JButton bttVerif1;
    private javax.swing.JTextField hitFailCantidad;
    private javax.swing.JTextField hitFailNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtEte;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombrePlatillo;
    private javax.swing.JTextArea txtReceta;
    // End of variables declaration//GEN-END:variables
}
