/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.Base64;
import modelado.Cliente;
import modelado.Direccion;
import modelado.PerfilAlimenticio;
import modelado.Platillo;
import modelado.Usuario;

/**
 *
 * @author bryan
 */
public class pantallaCrearCliente extends javax.swing.JFrame {

    /**
     * Creates new form prototipo
     */
     ArrayList<Usuario> usuarios;
     ArrayList<Direccion> dondeRecojerPedido;
     ArrayList<String> gustos;
     ArrayList<String> alergias;
    
    public pantallaCrearCliente(ArrayList<Usuario> usuarios) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarios= usuarios;
        this.dondeRecojerPedido= new ArrayList();
        this.gustos= new ArrayList();
        this.alergias= new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDinero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bttPerfilAlimenticio = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bttAddDirecciones = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("Fondos Disponibles:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 200, 120, 20);

        jLabel2.setText("Nombre De Usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 126, 19);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(110, 110, 110, 25);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(100, 30, 110, 25);

        jLabel3.setText("Nombre: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 30, 57, 19);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(170, 70, 110, 25);

        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 71, 20);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(180, 160, 90, 25);

        jLabel5.setText("Numero de telefono:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 124, 20);
        getContentPane().add(txtDinero);
        txtDinero.setBounds(180, 200, 90, 25);

        jLabel6.setText("Perfil Alimenticio:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 250, 114, 19);

        bttPerfilAlimenticio.setText("Crear Perfil Alimenticio");
        bttPerfilAlimenticio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPerfilAlimenticioActionPerformed(evt);
            }
        });
        getContentPane().add(bttPerfilAlimenticio);
        bttPerfilAlimenticio.setBounds(180, 250, 178, 30);

        jLabel7.setText("Agregar Direcciones donde retirar:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 300, 209, 19);

        bttAddDirecciones.setText("Añadir Direcciones a recojer");
        bttAddDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddDireccionesActionPerformed(evt);
            }
        });
        getContentPane().add(bttAddDirecciones);
        bttAddDirecciones.setBounds(240, 320, 205, 25);

        jButton1.setText("!Todo listo!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 120, 160, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Recursos Graficos/PantallaAddSistema.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 500, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre= this.txtNombre.getText();
        String usuarioID= this.txtUsuario.getText();
        int dinero= Integer.parseInt(this.txtDinero.getText());
        String telefono= this.txtTelefono.getText();
        String password= this.txtPassword.getText();
        String passwordCodificada = Base64.getEncoder().encodeToString(password.getBytes());
        PerfilAlimenticio perfil= new PerfilAlimenticio(gustos, alergias);
        ArrayList<Platillo> platillosAComprar= new ArrayList();
        Cliente nuevoCliente= new Cliente(telefono, dinero, dondeRecojerPedido, perfil, usuarioID, passwordCodificada, nombre, platillosAComprar);
 
        this.usuarios.add(nuevoCliente);
        this.setVisible(false);
        System.out.println("############CLIENTE#################");
        System.out.println(nuevoCliente.toString());
        System.out.println("############CLIENTE#################");
        System.out.println("\n");
        System.out.println("############TODOS LOS CLIENTE#################");
        System.out.println(usuarios.toString());
        System.out.println("############TODOS LOS CLIENTE#################");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bttPerfilAlimenticioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPerfilAlimenticioActionPerformed
        // TODO add your handling code here:
        pantallaCreadoraDePerfilAlimenticio nuevoPerfil= new pantallaCreadoraDePerfilAlimenticio(gustos, alergias);
        nuevoPerfil.setVisible(true);
    }//GEN-LAST:event_bttPerfilAlimenticioActionPerformed

    private void bttAddDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddDireccionesActionPerformed
        // TODO add your handling code here:
        pantallaCreadoraDeDirecciones addDestinos= new pantallaCreadoraDeDirecciones(dondeRecojerPedido);
        addDestinos.setVisible(true);
    }//GEN-LAST:event_bttAddDireccionesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAddDirecciones;
    private javax.swing.JButton bttPerfilAlimenticio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDinero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
