/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import modelado.ClaseApoyo;
import modelado.Direccion;
import modelado.Usuario;

/**
 *
 * @author bryan
 */
public class pantallaCreadoraDeDirecciones extends javax.swing.JFrame {

    ArrayList<Direccion> direcciones;
  
    public pantallaCreadoraDeDirecciones(ArrayList<Direccion> direcciones) {
       initComponents();
       this.setLocationRelativeTo(null);
       this.direcciones=direcciones;
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbutton = new javax.swing.JButton();
        bttAdd = new javax.swing.JButton();
        labelConfirmar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        txtLatitud1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(382, 356));
        getContentPane().setLayout(null);

        backbutton.setText("Volver");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(10, 290, 72, 20);

        bttAdd.setText("Añadir");
        bttAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAddActionPerformed(evt);
            }
        });
        getContentPane().add(bttAdd);
        bttAdd.setBounds(140, 240, 72, 20);
        getContentPane().add(labelConfirmar);
        labelConfirmar.setBounds(150, 270, 100, 30);

        jLabel3.setText("solo puedes añadir una, cada que presiones añadir!!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 307, 19);

        txtDireccion.setColumns(20);
        txtDireccion.setRows(5);
        jScrollPane1.setViewportView(txtDireccion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 340, 101);

        jLabel4.setText("Puedes añadir las direcciones que gustes, pero recuerda");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 30, 333, 19);

        jLabel1.setText("Longitud:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 90, 56, 19);

        jLabel2.setText("Latitud:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 46, 19);
        getContentPane().add(txtLongitud);
        txtLongitud.setBounds(260, 90, 80, 25);
        getContentPane().add(txtLatitud1);
        txtLatitud1.setBounds(90, 90, 80, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Recursos Graficos/LogoHoyComo.png"))); // NOI18N
        jLabel5.setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-60, 0, 460, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void bttAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAddActionPerformed
        // TODO add your handling code here:
        String texto= this.txtDireccion.getText();
        Double longitud= Double.parseDouble(this.txtLongitud.getText());
        Double latitud= Double.parseDouble(this.txtLatitud1.getText());
        Direccion nuevaDireccion= new Direccion(texto, latitud, longitud);
        this.direcciones.add(nuevaDireccion);
        this.labelConfirmar.setText("Añadido");
        this.txtDireccion.setText("");
        
        
    }//GEN-LAST:event_bttAddActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton bttAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelConfirmar;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextField txtLatitud1;
    private javax.swing.JTextField txtLongitud;
    // End of variables declaration//GEN-END:variables
}
