/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import modelado.Platillo;

/**
 *
 * @author bryan
 */
public class pantallaFactura extends javax.swing.JFrame {

    /**
     * Creates new form prototipo
     */
    ArrayList<Platillo> compra;
    public pantallaFactura(ArrayList<Platillo> compra) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.compra= compra;
        generarFactura(this.compra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 460, 280));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Recursos Graficos/LogoHoyComo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void generarFactura(ArrayList<Platillo> compra){
        int valorFinal=0;
       for(int i=0; i<compra.size();i++){
           valorFinal= valorFinal+compra.get(i).getCosto()*compra.get(i).getCantidad();
       }
       double valorConIva= valorFinal+valorFinal*0.13;
       double valorConGanancia= valorConIva+valorConIva*0.35;
       this.jTextArea1.setText("Tu carrito lo conforma: "+"\n"+compra.toString()+"\n"+"Con un valor de: "
               + valorFinal+"\n"+"Pero debes pagar: "+ valorConIva+"\n"+"Debido al IVA\n"+"Y además 35% debido a nuestra atencion\n"
       +"Para un total de:\n"+valorConGanancia);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
