/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import modelado.ClaseApoyo;
import modelado.Ingrediente;
import modelado.Platillo;
import modelado.Usuario;

/**
 *
 * @author bryan
 */
public class pantallaSeleccion extends javax.swing.JFrame {

    int tipo=0;
    ArrayList<Usuario> usuarios;
    ArrayList<Ingrediente> almacen;
    ArrayList<Platillo> oferta;
    public pantallaSeleccion(ArrayList<Usuario> usuarios,int tipo, ArrayList<Ingrediente> almacen,ArrayList<Platillo> oferta ) {
       initComponents();
       this.setLocationRelativeTo(null);
       this.tipo=tipo;
       this.usuarios=usuarios;
       this.almacen=almacen;
       this.oferta=oferta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginButton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        backbutton.setText("Volver");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jButton1.setText("Registrarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Recursos Graficos/PantallaSeleccionPequeñas.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -10, 250, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        ClaseApoyo apoyo= new ClaseApoyo();
        pantallaLogear pantalla= new pantallaLogear(this.usuarios, apoyo, this.tipo, this.almacen, this.oferta);
        pantalla.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(tipo==1){
            pantallaCrearCliente nuevoCliente= new pantallaCrearCliente(usuarios);
            nuevoCliente.setVisible(true);
            this.setVisible(false);
        }else if(tipo==2){
            pantallaCrearGeneral nuevaPantalla= new pantallaCrearGeneral(usuarios, tipo);
            nuevaPantalla.setVisible(true);
            this.setVisible(false);
            
        }else if(tipo== 3){
            pantallaCrearGeneral nuevaPantalla= new pantallaCrearGeneral(usuarios, tipo);
            nuevaPantalla.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    // End of variables declaration//GEN-END:variables
}
